# Generated by Django 5.2.6 on 2025-09-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
