# Generated by Django 5.2.6 on 2025-10-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seller_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='compliance_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10, null=True),
        ),
    ]
