# Generated by Django 5.2.6 on 2025-10-15 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_seller_compliance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to='sellers/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='seller',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='sellers/logos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
