# Generated by Django 5.2.6 on 2025-10-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_seller_documents_alter_seller_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
