# Generated by Django 5.2.6 on 2025-09-22 08:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_phone_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='masterproduct',
            name='name',
        ),
        migrations.RemoveField(
            model_name='masterproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='slug',
            field=models.CharField(default='temp-slug', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='masterproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('super_admin', 'Super Admin'), ('vendor', 'Vendor'), ('customer', 'Customer')], max_length=50),
        ),
    ]
