# Generated by Django 5.2.6 on 2025-11-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_seller_user_alter_category_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('super_admin', 'Super Admin'), ('vendor', 'Vendor'), ('customer', 'Customer')], max_length=50),
        ),
    ]
