# Generated by Django 5.2.6 on 2025-09-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_masterproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterproduct',
            name='name',
            field=models.CharField(default='temp-name', max_length=100),
        ),
    ]
